version: 2.1
executors:
  docker-publisher:
    environment:
      LATEST: tomashgombosh/chrome-firefox:latest
      GRID: tomashgombosh/chrome-firefox:grid-latest
      JRE_11: tomashgombosh/chrome-firefox:jre-11
      NODE_16: tomashgombosh/chrome-firefox:node-16
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Prepare build files"
          command: | 
            ./build.sh jre-17
            ./build.sh jre-17-grid     
            ./build.sh jre-11      
            ./build.sh node-16                 
      - run:
          name: Build Docker image
          command: |
            cd jre-17 && docker build -t $LATEST . && cd ..
            cd jre-11 && docker build -t $JRE_11 . && cd ..          
            cd jre-17-grid && docker build -t $GRID . && cd ..                
      - run:
          name: Archive Docker image
          command: |
            docker save -o latest.tar $LATEST
            docker save -o grid.tar $GRID
            docker save -o java_11.tar $JRE_11
      - persist_to_workspace:
          root: .
          paths:
            - ./latest.tar 
            - ./grid.tar 
            - ./java_11.tar                         
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: | 
            docker load -i /tmp/workspace/latest.tar
            docker load -i /tmp/workspace/grid.tar
            docker load -i /tmp/workspace/java_11.tar                        
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $LATEST
            docker push $GRID
            docker push $JRE_11

workflows:
  version: 2.1
  build-develop:
    jobs:     
      - build:
          filters:
            branches:
              only: develop
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: develop              