version: 2.1
executors:
  docker-publisher:
    environment:
      GRID_VERSION: "4.12.1"
      CHROMEDRIVER_VERSION: "117.0.5938.88"
      GECKODRIVER_VERSION: "0.33.0"
      MAVEN_VERSION: "3.9.4"
      LATEST: tomashgombosh/chrome-firefox:latest
      GRID: tomashgombosh/chrome-firefox:grid
      GRID_JRE_17: tomashgombosh/chrome-firefox:jre-17-grid
      JRE_11: tomashgombosh/chrome-firefox:jre-11
      JRE_17: tomashgombosh/chrome-firefox:jre-17
      NODE_16: tomashgombosh/chrome-firefox:node-16
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  unit_tests:
    executor: docker-publisher
    parallelism: 5
    resource_class: large

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare environment variables
          command: |
            ./prepare_vars.sh 
            ./build.sh
      - run:
          name: Running Test
          command: sh ./tests_handler.sh

  latest:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Prepare build files"
          command: |
            ./build.sh jre-18
      - run:
          name: Build Docker image
          command: |
            cd jre-18 && docker build \
            --build-arg CHROMEDRIVER_VERSION=$CHROMEDRIVER_VERSION \
            --build-arg GECKODRIVER_VERSION=$GECKODRIVER_VERSION \
            --build-arg MAVEN_VERSION=$MAVEN_VERSION \
            -t $LATEST .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $LATEST

  jre-11:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Prepare build files"
          command: |
            ./build.sh jre-11
      - run:
          name: Build Docker image
          command: |
            cd jre-11 && docker build \
            --build-arg CHROMEDRIVER_VERSION=$CHROMEDRIVER_VERSION \
            --build-arg GECKODRIVER_VERSION=$GECKODRIVER_VERSION \
            --build-arg MAVEN_VERSION=$MAVEN_VERSION \
            -t $JRE_11 .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $JRE_11
  jre-17:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Prepare build files"
          command: |
            ./build.sh jre-17
      - run:
          name: Build Docker image
          command: |
            cd jre-17 && docker build \
            --build-arg CHROMEDRIVER_VERSION=$CHROMEDRIVER_VERSION \
            --build-arg GECKODRIVER_VERSION=$GECKODRIVER_VERSION \
            --build-arg MAVEN_VERSION=$MAVEN_VERSION \
            -t $JRE_17 .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $JRE_17
  grid:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Prepare build files"
          command: |
            ./build.sh jre-18-grid
      - run:
          name: Build Docker image
          command: |
            cd jre-18-grid && docker build \
            --build-arg SELENIUM_GRID_VERSION=$GRID_VERSION \
            --build-arg CHROMEDRIVER_VERSION=$CHROMEDRIVER_VERSION \
            --build-arg GECKODRIVER_VERSION=$GECKODRIVER_VERSION \
            -t $GRID .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $GRID
  grid-jre-17:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Prepare build files"
          command: |
            ./build.sh jre-17-grid
      - run:
          name: Build Docker image
          command: |
            cd jre-17-grid && docker build \
            --build-arg SELENIUM_GRID_VERSION=$GRID_VERSION \
            --build-arg CHROMEDRIVER_VERSION=$CHROMEDRIVER_VERSION \
            --build-arg GECKODRIVER_VERSION=$GECKODRIVER_VERSION \
            -t $GRID_JRE_17 .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $GRID_JRE_17
  node:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Prepare build files"
          command: |
            ./build.sh node-16
      - run:
          name: Build Docker image
          command: |
            cd node-16 && docker build \
            --build-arg CHROMEDRIVER_VERSION=$CHROMEDRIVER_VERSION \
            --build-arg GECKODRIVER_VERSION=$GECKODRIVER_VERSION \
            -t $NODE_16 .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $NODE_16

workflows:
  version: 2
  build:
    jobs:
      - unit_tests
      - latest:
          filters:
            branches:
              only: develop
      - grid:
          filters:
            branches:
              only: develop              
      - jre-11:
          filters:
            branches:
              only: develop
      - jre-17:
          filters:
            branches:
              only: develop
      - grid-jre-17:
          filters:
            branches:
              only: develop                      
      - node:
          filters:
            branches:
              only: develop
