version: 2.1
executors:
  docker-publisher:
    environment:
      LATEST: tomashgombosh/chrome-firefox:latest
      GRID: tomashgombosh/chrome-firefox:grid-latest
      JRE_11: tomashgombosh/chrome-firefox:jre-11
      NODE_16: tomashgombosh/chrome-firefox:node-16
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  latest:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Prepare build files"
          command: | 
            ./build.sh jre-17                
      - run:
          name: Build Docker image
          command: |
            cd jre-17 && docker build -t $LATEST . && cd ..                      
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $LATEST                
  jre-11:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Prepare build files"
          command: | 
            ./build.sh jre-11              
      - run:
          name: Build Docker image
          command: |
            cd jre-11 && docker build -t $JRE_11 . && cd ..                      
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $JRE_11

  grid:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Prepare build files"
          command: | 
            ./build.sh jre-17-grid             
      - run:
          name: Build Docker image
          command: |
            cd jre-17-grid && docker build -t $GRID . && cd ..                      
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $GRID
  node:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Prepare build files"
          command: | 
            ./build.sh node-16           
      - run:
          name: Build Docker image
          command: |
            cd node-16 && docker build -t $NODE_16 . && cd ..                      
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $NODE_16            

workflows:
  version: 2.1
  build:
    jobs:     
      - latest:
          filters:
            branches:
              only: develop
      - jre-11:
          filters:
            branches:
              only: develop     
      - grid:
          filters:
            branches:
              only: develop    
      - node:
          filters:
            branches:
              only: develop                               