name: Hadolint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  hadolint:
    name: Run hadolint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hadolint JRE 11
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./jre-11/Dockerfile
          format: sarif
          output-file: hadolint.sarif
          no-fail: true

      - name: Run hadolint JRE 17
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./jre-17/Dockerfile
          format: sarif
          output-file: hadolint.sarif
          no-fail: true

      - name: Run hadolint GRID
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./jre-17-grid/Dockerfile
          format: sarif
          output-file: hadolint.sarif
          no-fail: true

      - name: Run hadolint Node 16
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./node-16/Dockerfile
          format: sarif
          output-file: hadolint.sarif
          no-fail: true

      - name: Upload analysis to the GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint.sarif
          wait-for-processing: true      