name: Linter

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: read

jobs:
  hadolint:
    name: Run scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hadolint JRE 11
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./jre-11/Dockerfile
          format: sarif
          output-file: hadolint-jre-11.sarif
          no-fail: true

      - name: Run hadolint JRE 17
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./jre-17/Dockerfile
          format: sarif
          output-file: hadolint-jre-17.sarif
          no-fail: true

      - name: Run hadolint GRID
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./jre-17-grid/Dockerfile
          format: sarif
          output-file: hadolint-grid.sarif
          no-fail: true

      - name: Run hadolint Node 16
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./node-16/Dockerfile
          format: sarif
          output-file: hadolint-node-16.sarif
          no-fail: true

      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: "scripts/*.sh, jre-17-grid/*.sh, jre-17-grid/scripts/*.sh, node-16/scripts/*.sh"
          severity: "error"

      - name: Upload analysis JRE-11
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: jre-11
          sarif_file: hadolint-jre-11.sarif
          wait-for-processing: true

      - name: Upload analysis JRE-17
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: jre-17
          sarif_file: hadolint-jre-17.sarif
          wait-for-processing: true

      - name: Upload analysis GRID
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: grid
          sarif_file: hadolint-grid.sarif
          wait-for-processing: true

      - name: Upload analysis Node
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: node-16
          sarif_file: hadolint-node-16.sarif
          wait-for-processing: true
